# Generated by Django 3.2.18 on 2023-02-14 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarInsurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinsurance',
            name='mileage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='carinsurance',
            name='year',
            field=models.PositiveIntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023),
        ),
    ]
